-- ─── review_ai_analysis: fix column schema mismatches ────────────────────────
--
-- Three issues discovered during AI reasoning lifecycle trace:
--
--  1. The `reasoning` column is `text` but the application inserts a
--     `string[]` and reads it back expecting an array.  PostgREST returns a
--     `text` value as a JS string, causing `Array.isArray()` to return false
--     and the UI to always show "No reasoning generated yet."
--     Fix: cast to `jsonb not null default '[]'::jsonb`.
--
--  2. The `summary` column does not exist in the live (migration 2) schema,
--     causing a silent PostgREST null on every SELECT and a PGRST204 on
--     INSERTs that include it.
--     Fix: add `summary text`.
--
-- The third mismatch (`recommendation_confidence` vs `confidence` and
-- `engine` vs `model`) is fixed in application code only — no DDL needed.

-- ── 1. Add summary column ─────────────────────────────────────────────────────

alter table public.review_ai_analysis
  add column if not exists summary text;

comment on column public.review_ai_analysis.summary is
  'One-to-two sentence factual summary generated by the AI copilot.';

-- ── 2. Cast reasoning from text to jsonb ──────────────────────────────────────
--
-- Existing rows almost certainly have NULL (inserts were failing due to the
-- `engine` column mismatch that also blocked this column from being written).
-- The USING expression handles all three realistic cases:
--   • NULL           → '[]'
--   • ''             → '[]'
--   • valid JSON str → parsed jsonb array
-- A non-JSON string would cause this migration to fail loudly rather than
-- silently corrupt data — intentional.

alter table public.review_ai_analysis
  alter column reasoning
    type jsonb
    using case
      when reasoning is null or reasoning = ''
        then '[]'::jsonb
      else reasoning::jsonb
    end;

-- Back-fill any remaining NULLs that survived the USING clause (shouldn't
-- happen given the CASE above, but belt-and-suspenders before setting NOT NULL).
update public.review_ai_analysis
  set reasoning = '[]'::jsonb
  where reasoning is null;

alter table public.review_ai_analysis
  alter column reasoning set not null;

alter table public.review_ai_analysis
  alter column reasoning set default '[]'::jsonb;

comment on column public.review_ai_analysis.reasoning is
  'Ordered list of factual observations produced by the AI copilot (jsonb array of strings).';
