-- ─── Downstream Pipeline Permissions ─────────────────────────────────────────
--
-- Fixes two classes of "permission denied" errors that block the downstream
-- fraud-analysis and audit-trail pipeline after a successful OCR extraction:
--
--   1. fraud_signal_type enum — extend with all signal types generated by
--      lib/fraud/generate-signals.ts and lib/actions/ocr.ts.  The DB enum
--      only has 12 generic values; our engine emits 16 fine-grained ones.
--
--   2. review_events — table was created without RLS or GRANTs.
--      Enable RLS + add SELECT + INSERT policies for org members.
--
--   3. fraud_signals — table exists but has no INSERT policy for
--      authenticated users.  Add SELECT + INSERT policies.
--
-- Security model
-- ──────────────
-- Both tables are scoped to reviews that belong to the caller's active org
-- membership.  System pipeline events (actor_type = 'system') are emitted
-- from the authenticated user's server-action context — the user's session
-- is present and auth.uid() resolves correctly.
-- ─────────────────────────────────────────────────────────────────────────────


-- ╔══════════════════════════════════════════════════════════════════════════════
-- ║ PART 1 — Extend fraud_signal_type enum
-- ╚══════════════════════════════════════════════════════════════════════════════

-- OCR quality signals
alter type public.fraud_signal_type add value if not exists 'low_ocr_confidence';
alter type public.fraud_signal_type add value if not exists 'blurry_document';
alter type public.fraud_signal_type add value if not exists 'unreadable_regions';

-- Completeness signals
alter type public.fraud_signal_type add value if not exists 'missing_vendor';
alter type public.fraud_signal_type add value if not exists 'missing_invoice_number';
alter type public.fraud_signal_type add value if not exists 'missing_amount';
alter type public.fraud_signal_type add value if not exists 'missing_date';

-- Consistency signals
alter type public.fraud_signal_type add value if not exists 'invalid_date_format';
alter type public.fraud_signal_type add value if not exists 'impossible_amount';
alter type public.fraud_signal_type add value if not exists 'suspicious_currency_format';

-- Screenshot signals
alter type public.fraud_signal_type add value if not exists 'cropped_screenshot';
alter type public.fraud_signal_type add value if not exists 'inconsistent_odds_format';

-- Generic signals
alter type public.fraud_signal_type add value if not exists 'suspicious_formatting';
alter type public.fraud_signal_type add value if not exists 'excessive_missing_fields';

-- Sportsbook-specific signals
alter type public.fraud_signal_type add value if not exists 'transaction_pattern';

-- Duplicate signals
alter type public.fraud_signal_type add value if not exists 'duplicate_submission';
alter type public.fraud_signal_type add value if not exists 'ocr_text_duplicate';


-- ╔══════════════════════════════════════════════════════════════════════════════
-- ║ PART 2 — review_events: enable RLS + grant + policies
-- ╚══════════════════════════════════════════════════════════════════════════════

alter table public.review_events enable row level security;

grant select, insert on public.review_events to authenticated;

-- Members can read all events for reviews in their active org(s).
create policy "review_events_select_org_member"
  on public.review_events
  for select
  using (
    review_id in (
      select r.id
      from   public.reviews r
      join   public.organization_members om
               on om.organization_id = r.organization_id
      where  om.user_id = auth.uid()
        and  om.status  = 'active'
    )
  );

-- Members can emit pipeline events for reviews in their active org(s).
-- (Both actor_type = 'system' and actor_type = 'human' go through this policy.)
create policy "review_events_insert_org_member"
  on public.review_events
  for insert
  with check (
    review_id in (
      select r.id
      from   public.reviews r
      join   public.organization_members om
               on om.organization_id = r.organization_id
      where  om.user_id = auth.uid()
        and  om.status  = 'active'
    )
  );

comment on table public.review_events is
  'Immutable pipeline event log: OCR_COMPLETED, FRAUD_ANALYSIS_COMPLETED, '
  'AI_ANALYSIS_COMPLETED, REVIEW_APPROVED, REVIEW_REJECTED, etc. '
  'Inserted by authenticated users (via server actions or SECURITY DEFINER RPCs).';


-- ╔══════════════════════════════════════════════════════════════════════════════
-- ║ PART 3 — fraud_signals: grant + policies
-- ╚══════════════════════════════════════════════════════════════════════════════

-- RLS is already enabled on fraud_signals (table was created externally).
-- We only need to add the missing GRANT + policies.

grant select, insert on public.fraud_signals to authenticated;

-- Members can read fraud signals for reviews in their org.
create policy "fraud_signals_select_org_member"
  on public.fraud_signals
  for select
  using (
    organization_id in (
      select organization_id
      from   public.organization_members
      where  user_id = auth.uid()
        and  status  = 'active'
    )
  );

-- Members can write fraud signals for reviews in their org.
-- (Only the OCR server action writes these; org-membership is the correct scope.)
create policy "fraud_signals_insert_org_member"
  on public.fraud_signals
  for insert
  with check (
    organization_id in (
      select organization_id
      from   public.organization_members
      where  user_id = auth.uid()
        and  status  = 'active'
    )
  );
